version: "3"

services:
  app:
    image: webdevops/php-apache-dev:5.6
    depends_on:
      - db
    ports:
      - 8080:80
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app
    volumes:
      - './:/app'
  db:
    image: mysql:5.6
    volumes:
      - mysql_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stugsa
      MYSQL_DATABASE: stugsa
    ports:
      - "3306:3306"
volumes:
  mysql_db_data: